SET STATISTICS TIME ON;
SET STATISTICS PROFILE ON;
SET STATISTICS IO ON;
SET STATISTICS XML ON;

SELECT * FROM [dbo].[Order]
UNION --ALL to save duplicates
SELECT * FROM [dbo].[ArchivedOrder]

SET STATISTICS XML OFF;
SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
SET STATISTICS PROFILE OFF;